
// declare module 'react-beautiful-dnd'
// declare module 'react-albus'
// declare module 'fullcalendar-reactwrapper'
// declare module 'react-signature-canvas'
// declare module 'react-router-dom'
// declare module 'react-router'
// declare module 'rc-color-picker'
// declare module 'react-confirm-alert'
// declare module 'react-input-mask'
// declare module 'react-summernote'
// declare module 'react-jsonschema-form'
// declare module 'react-render-html'
// declare module 'react-html-parser'

// declare module 'react-loadable'

// // declare module 'react-images-upload'
// declare module 'react-filepond'
// declare module 'filepond-plugin-image-preview'
// declare module 'filepond-plugin-file-validate-type'

// declare module '*.svg'
declare module '*.mp3'
// declare module '*.jpg'